---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# HTEBand

<!-- badges: start -->
<!-- badges: end -->

The goal of HTEBand is to construct uniform confidence bands for various types of heterogenous treatment effect parameters. 

## Installation

You can install the development version from [GitHub](https://github.com/) with:

``` r
install.packages("remotes") # if not installed
remotes::install_github("koohyun-kwon/HTEBand")
```

## Example

Nonparametric regression via `NpregBand()`:

```{r example}
library(HTEBand)
library(tidyverse)
x <- seq(-1, 1, length.out = 500)
y <- x^2 + rnorm(500, 0, 1/4)
cb.res <- NpregBand(y, x, 2, 0.95, "L", n.eval = 25)
cb.res$fx <- (cb.res$eval)^2
ggplot(data = cb.res) + geom_line(aes(x = eval, y = cb.lower)) +
  geom_line(aes(x = eval, y = cb.upper)) + geom_line(aes(x = eval, y = fx), color = "red")
```
